In [3]:
import numpy as np

Answer no 1

In [4]:
arr=np.arange(2,51,5)

In [5]:
arr

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

Answer no 2

In [10]:
a=list(input("Enter the first list "))
b=list(input("Enter the second list "))

Enter the first list 75942
Enter the second list 37154


In [17]:
np.array(a)

array(['7', '5', '9', '4', '2'], dtype='<U1')

In [12]:
np.array(b)

array(['3', '7', '1', '5', '4'], dtype='<U1')

In [26]:
c=np.concatenate((a,b),axis=0)

In [25]:
c=c.astype(int)

In [22]:
c

array([7, 5, 9, 4, 2, 3, 7, 1, 5, 4])

In [23]:
sorted(c)

[1, 2, 3, 4, 4, 5, 5, 7, 7, 9]

Answer no 3

In [28]:
w=np.array([[1,5,7],[2,5,4]])

In [32]:
w.shape

(2, 3)

In [33]:
w.size

6

Answer no 4

In [39]:
p=np.array([2,4,5,7,6,4])

In [40]:
p.reshape(2,3)

array([[2, 4, 5],
       [7, 6, 4]])

In [41]:
p_new=p[:,np.newaxis]

In [42]:
p_new

array([[2],
       [4],
       [5],
       [7],
       [6],
       [4]])

Answer no 5

In [45]:
e=np.array([[2,4],[5,8]])
f=np.array([[2,8],[2,6]])

In [47]:
np.vstack(e)

array([[2, 4],
       [5, 8]])

In [48]:
np.hstack(f)

array([2, 8, 2, 6])

Answer no 6

In [62]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
